name: dropmate-backend
region: nyc

# PostgreSQL Database
databases:
  - name: dropmate-db
    engine: PG
    version: "16"
    production: false
    cluster_name: dropmate-cluster

# Services
services:
  # Core API Service
  - name: core-api
    github:
      repo: kevinlin29/dropmate-backend
      branch: main
      deploy_on_push: true
    source_dir: /services/core-api
    dockerfile_path: services/core-api/Dockerfile
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
    envs:
      - key: PORT
        value: "8080"
      - key: DATABASE_URL
        value: ${dropmate-db.DATABASE_URL}
      - key: JWT_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: NODE_ENV
        value: "production"
      - key: FIREBASE_PROJECT_ID
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: FIREBASE_CLIENT_EMAIL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: FIREBASE_PRIVATE_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
    health_check:
      http_path: /health

  # Location Service
  - name: location-service
    github:
      repo: kevinlin29/dropmate-backend
      branch: main
      deploy_on_push: true
    source_dir: /services/location-service
    dockerfile_path: services/location-service/Dockerfile
    http_port: 8081
    instance_count: 1
    instance_size_slug: basic-xxs
    internal_ports:
      - 8081
    envs:
      - key: PORT
        value: "8081"
      - key: DATABASE_URL
        value: ${dropmate-db.DATABASE_URL}
      - key: REDIS_URL
        value: ${redis.REDIS_URL}
      - key: NODE_ENV
        value: "production"
    health_check:
      http_path: /health

  # Notification Service (WebSocket)
  - name: notification-service
    github:
      repo: kevinlin29/dropmate-backend
      branch: main
      deploy_on_push: true
    source_dir: /services/notification-service
    dockerfile_path: services/notification-service/Dockerfile
    http_port: 8082
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /ws
    envs:
      - key: PORT
        value: "8082"
      - key: REDIS_URL
        value: ${redis.REDIS_URL}
      - key: CORS_ORIGIN
        value: "*"
      - key: NODE_ENV
        value: "production"
    health_check:
      http_path: /health

# Redis for pub/sub
workers:
  - name: redis
    image:
      registry_type: DOCR
      registry: redis
      repository: redis
      tag: "7-alpine"
    instance_count: 1
    instance_size_slug: basic-xxs
